import Main from "./Main";
import "./globals.css";

export const metadata = {
  title: "Escuela Normal Superior de Ibagué",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Main>{children}</Main>
    </html>
  );
}
